site_settings:
  title: "Dynamic Zoom: Enhancing Video Resolution in Real-Time"
  description: >
    Explore Dynamic Zoom, our innovative real-time super-resolution technique tailored for digital media. Designed as a project for UW-Madison - ECE 766, this work leverages the cutting-edge Bicubic++ model to deliver high-definition video content without the usual degradation during zoom. Perfect for creators and consumers aiming for precision and clarity in dynamic video segments.
  show_downloads: true
  theme: jekyll-theme-cayman
